CREATE TABLE Categories
(
Id INT PRIMARY KEY IDENTITY(1,1),
[Name] NVARCHAR(30) NOT NULL
)




CREATE TABLE Items
(
Id INT PRIMARY KEY IDENTITY(1,1),
[Name] NVARCHAR(30) NOT NULL,
Price DECIMAL(15,2) NOT NULL,
CategoryId INT FOREIGN KEY REFERENCES Categories(Id) NOT NULL
)

CREATE TABLE Employees
(
Id INT PRIMARY KEY IDENTITY(1,1),
FirstName NVARCHAR(50) NOT NULL,
LastName NVARCHAR(50) NOT NULL,
Phone CHAR(15) NOT NULL,
Salary DECIMAL(15,2) NOT NULL
)

CREATE TABLE Orders
(
Id INT PRIMARY KEY IDENTITY(1,1),
[DateTime] DATETIME NOT NULL,
EmployeeId INT FOREIGN KEY REFERENCES Employees(Id) NOT NULL
)


CREATE TABLE OrderItems
(
OrderId INT NOT NULL,
ItemId INT NOT NULL,
Quantity INT DEFAULT(1) NOT NULL,

CONSTRAINT PK_OrderItems PRIMARY KEY (OrderId,ItemId),

CONSTRAINT FK_Order FOREIGN KEY (OrderId) REFERENCES Orders(Id),
CONSTRAINT FK_Item FOREIGN KEY (ItemId) REFERENCES Items(Id)
)

CREATE TABLE Shifts
(
Id INT IDENTITY NOT NULL,
EmployeeId INT NOT NULL,
CheckIn DATETIME NOT NULL,
CheckOut DATETIME NOT NULL,


CONSTRAINT CheckOut_Check CHECK (CheckOut > CheckIn),

CONSTRAINT Id_EmployeeID PRIMARY KEY  (Id,EMployeeId),
CONSTRAINT Employees_Id FOREIGN KEY (EmployeeId) REFERENCES Employees(Id)

)